name: Setup CI/CD
description: Common CI/CD setup for The Westervelt Company
inputs:
  python-version:
    description: The version of Python to setup
    required: true
    default: "3.12"
  node-version:
    description: The version of Node.js to setup
    required: true
    default: "20"
runs:
  using: composite
  steps:
    - shell: bash
      run: sudo chown -R $(whoami) /github/home

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        python -m pip install -U pip uv

    - name: Get cache dir
      id: py-cache
      shell: bash
      run: |
        echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.py-cache.outputs.dir }}
        key: ${{ runner.os }}-py-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-py-

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Get npm cache dir
      id: npm-cache
      shell: bash
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - uses: extractions/setup-just@v2
